### ISSUE TITLE
如果在云服务器上运行，没有配置代理需要注释掉这段代码，避免出现模型加载失败情况

### ISSUE THREAD

**Issue by XksA-me** [X-D-Lab/LangChain-ChatGLM-Webui#108]
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/ce46a756-4ab1-42ba-91bc-e96a95847a1b)

由于作者做了异常处理，如果没有配置代理或者端口不一致，可能直接显示“模型未成功重新加载，请点击重新加载模型”，而不清楚错误原因，建议这部分加些日志输出打印错误原因

![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/f13d5d20-c6ce-429e-8019-7628414d468f)

**Comment by XksA-me** [comment]
app.py 文件

**Comment by XksA-me** [comment]
记录下我在 matpool.com 复现过程：
租用环境：Pytorch 2.0
1、安装运行步骤：
github 链接前加国内源可以加速下载，安装包也一样，如果是从github安装，在github链接前加上国内源即可：https://ghproxy.com/
```bash
git clone https://ghproxy.com/https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui
cd LangChain-ChatGLM-Webui/
pip install -r requirements.txt 
```
2、环境配置好，放模型，我的模型下载上传在矩池云网盘，目录是 /mnt/example/chatglm-6b

3、修改配置代码：把模型相对路径改下自己模型存放位置的绝对路径，就是上面写的，你要改成你自己模型所在位置
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/902fb530-85c0-4411-9910-04a2aa91edd1)

我只测试下 chatglm-6b，所以把默认模型改成了 chatglm-6b。
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/540e765f-525e-49d8-914a-45762fbf1e70)


4、修改app.py代码：注释代理配置代码。

![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/057b5580-9d69-4176-84ff-80138359a5cb)

另外加了两个print打印异常信息，方便日志排查问题。
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/36f7a9e1-e613-4da9-a1cc-221975e0608b)

5、运行代码：
```bash
cd LangChain-ChatGLM-Webui/
python app.py
```
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/b675ef61-64f0-4717-a52b-6d0f4b414611)
第一次启动会要下载写模型，国内访问huggingface时快时慢。。。如果有啥错误多运行几次，或者本地下载好上传到服务器。

6、页面显示
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/84d061cd-9d21-4311-b3d2-e0717f0ff622)


随便创建一个123.txt文件
<img width="695" alt="image" src="https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/1ca6f00f-7e51-4ca5-9241-9f09095f3af0">

文件sh上传完成后，需要点下`知识库文件向量化`，然后就可以开始提问啦
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/3465563c-0f83-48b3-a372-e0509517583b)

7、提问
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/43670614/f29da40b-87e3-49b3-82fa-a0b386cadcdd)
整体体验比较好，因为给的数据有限，所以效果自然有限，欢迎大家指正交流。

**Comment by thomas-yanxin** [comment]
如果可以提个PR趴~

**Comment by ev2li** [comment]
不在服务器上设置代理，没有办法获得到public url
