### ISSUE TITLE
无法加载模型

### ISSUE THREAD

**Issue by wiizz3** [X-D-Lab/LangChain-ChatGLM-Webui#137]
![屏幕截图 2023-12-17 140726](https://github.com/X-D-Lab/LangChain-ChatGLM-Webui/assets/147958612/7c173b00-1daa-40be-88ea-ce12138035b2)
![屏幕截图 2023-12-17 140803](https://github.com/X-D-Lab/LangChain-ChatGLM-Webui/assets/147958612/7bff01ba-9790-4d55-af2a-fcb028ebde0f)
环境配置都没问题，就是模型这里有问题
我可以单独打开chatglm的webui，但是我无法加载

**Comment by wiizz3** [comment]
Name: transformers
Version: 4.36.1
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: F:\anaconda\Lib\site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: fschat, peft, sentence-transformers, transformers-stream-generator, unstructured-inference

这是我的transformers的版本

**Comment by thomas-yanxin** [comment]
降一下transformers的版本
