### ISSUE TITLE
启智：gradio创建外部访问连接超时

### ISSUE THREAD

**Issue by wmtlike** [X-D-Lab/LangChain-ChatGLM-Webui#141]
启智运行程序，gradio创建外部链接超时，gradio版本3.10.0 是什么原因呢。
Running on local URL:  http://0.0.0.0:7860
*** Failed to connect to ec2.gradio.app:22: [Errno 110] Connection timed out

**Comment by thomas-yanxin** [comment]
此方法对启智环境已不再适用。可以换个环境。

**Comment by wmtlike** [comment]
好的，谢谢啦
