### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by qy-70** [X-D-Lab/LangChain-ChatGLM-Webui#153]
(chatglm1) D:\project\python-xm\LangChain-ChatGLM-Webui>python app.py
D:\Anaconda\Anaconda\envs\chatglm1\Lib\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.document_loaders import UnstructuredFileLoader`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
D:\Anaconda\Anaconda\envs\chatglm1\Lib\site-packages\langchain\vectorstores\__init__.py:35: LangChainDeprecationWarning: Importing vector stores from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.vectorstores import FAISS`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Traceback (most recent call last):
  File "D:\project\python-xm\LangChain-ChatGLM-Webui\app.py", line 16, in <module>
    from chatllm import ChatLLM
  File "D:\project\python-xm\LangChain-ChatGLM-Webui\chatllm.py", line 5, in <module>
    from fastchat.conversation import (compute_skip_echo_len,
ModuleNotFoundError: No module named 'fastchat'

**Comment by damon-ldl** [comment]
安装一下pip install fschat==0.2.3
